### ISSUE TITLE
Demo in docs?

### ISSUE THREAD

**Issue by Mister-Hope** [BeiyanYunyi/sodesu#1]
Why not add a demo in docs?

**Comment by BeiyanYunyi** [comment]
I'm writing docs. Before I finished it, you can see https://stblog.penclub.club/ .

**Comment by BeiyanYunyi** [comment]
Finished in bf1a273.

Because I'm lazy, I have used the serverURL from the Waline documentation and all comment will be storaged under paths that start with `/sodesu`.

If you don't want sodesu's documentation pages to use your server, just delete them and inform me.

@lizheming
