### ISSUE TITLE
感谢开源，遇到了几个问题

### ISSUE THREAD

**Issue by nanqic** [BeiyanYunyi/sodesu#12]
在react中使用时，遇到的问题
1. cdn的css位置错了
2. 切换页面会挂载多个评论，同样方式waline client不会
3. 有些配置为兼容waline client，如         `copyright: false,        dark: 'auto'`

我是动态引入的，代码如下
``` javascript
    const walineInstanceRef = useRef<any>(null);
    const containerRef = useRef(null);
    const loadWalineClient = async () => {
        //@ts-expect-error dynamic
        await import('https://unpkg.com/sodesu-comment/dist/sodesu.aio.umd.js');
        // @ts-expect-error
        return window.Sodesu.init;
    };

    useEffect(() => {
        const linkTag = document.createElement('link');
        linkTag.rel = 'stylesheet';
        linkTag.href = 'https://unpkg.com/sodesu-comment/dist/sodesu-comment.css';
        document.head.appendChild(linkTag);
        const initWaline = async () => {
            const walineClient = await loadWalineClient();
            walineInstanceRef.current = walineClient({
                ...defaultOptions,
                el: containerRef.current
            });
        };
        initWaline();
        localStorage.setItem('WALINE_COMMENT_BOX_EDITOR', '')

        return () => walineInstanceRef.current?.destroy();
    }, [location.pathname]);
    ```
    
    希望未来版本更好，有一天能平替官方版

**Comment by BeiyanYunyi** [comment]
具体场景有源码吗？我看一眼，React 使用起来可能是需要多凹一些代码

**Comment by BeiyanYunyi** [comment]
`copyright` 是关不掉的，这是由于 AGPL 协议而[有意为之](https://beiyanyunyi.github.io/sodesu/trade-offs#%E5%85%B3%E9%97%AD%E9%A1%B5%E8%84%9A%E7%89%88%E6%9D%83%E4%BF%A1%E6%81%AF)：源码需随服务（网页）一起提供。

**Comment by nanqic** [comment]
> 具体场景有源码吗？我看一眼，React 使用起来可能是需要多凹一些代码

上面就是Comment组件的源码。|
已经用回waline了，反正是懒加载，体积大一些不会影响首屏加载速度

**Comment by BeiyanYunyi** [comment]
我之后有空给个 React 示例吧。

**Comment by BeiyanYunyi** [comment]
以下代码可以解决你的问题 2。在我看来这可能是 React 在 API 设计上的问题。

这段代码是针对 React 19 环境编写的。在这段代码中，我使用了 React 19 的新特性 `use`，并且使用了其定义的 ref callback 新的清理副作用的方式（18 以前不能通过返回一个函数的方式来做到清除，需要判断 el 是否为 null，为 null 则执行清除，未来这个特性会被标记为 deprecated）。

```tsx
import { type FC, use, useCallback } from "react";
import { useLocation } from "react-router";

// Or use CDN URL
import sodesuCssUrl from "sodesu-comment/dist/sodesu-comment.css?url";
// Or use CDN URL
const sodesuPromise = import("sodesu-comment/aio");

const Comments: FC = () => {
  const sodesu = use(sodesuPromise);
  const location = useLocation();
  const divCallbackRef = useCallback(
    (el: HTMLDivElement) => {
      if (!el) return;
      sodesu.default.init({
        el,
        serverURL: "preserved",
        path: location.pathname,
      });
      return () => {
        sodesu.default.update({ path: location.pathname });
        el.innerHTML = "";
      };
    },
    [sodesu, location.pathname]
  );

  return (
    <>
      <link rel="stylesheet" href={sodesuCssUrl} />
      <div ref={divCallbackRef} />
    </>
  );
};

export default Comments;
```

**Comment by nanqic** [comment]
@BeiyanYunyi 感谢您提供的详细demo。是这样的，我的站点面向的用户并不是懂代码的程序员，想隐藏版权以更加简洁，请问是否违反协议？违反的话就只能继续用waline client了

**Comment by BeiyanYunyi** [comment]
我博客面向的用户也不是程序员。不过，考虑到确实会有人出于设计原因而不愿展示 `Powered by` 信息，我可以给 `copyright` 这一段添加一个开关来隐藏它，条件是：

1. 使用 `display: none` 这样的形式，从而让该元素在页面上[不被渲染](https://developer.mozilla.org/zh-CN/docs/Web/CSS/display#none)，但仍然出现在渲染后的 HTML 源码里。
2. 在控制台 `console.log` 出来。

从而在照顾到普通用户观感的同时，也保证技术爱好者可以根据需要而获得源码。对此你有什么想法，哪一种比较好，或者两种一起来？

**Comment by nanqic** [comment]
谢谢，两种都可以接受，隐藏更简单一些吧~

**Comment by BeiyanYunyi** [comment]
嗯，准备在 `0.4.0` 加上，我加好了回来说

**Comment by BeiyanYunyi** [comment]
完事儿了。注意 API 有所更改，可以参阅[最新的文档](https://beiyanyunyi.github.io/sodesu/guide/getting-started)来作调整。

**Comment by nanqic** [comment]
非常感谢，上面的问题都解决了，已经用上啦~
只是新版的评论样式会被父级影响，比如父级div `textAlign={"center"}`，评论内容都居中了，上个版本好像没受影响。
另外这个配置 `commentClassName: 'prose prose-neutral dark:prose-invert min-w-0 max-w-none'` 是UnoCSS 相关的类吗？不熟悉这个。

**Comment by BeiyanYunyi** [comment]
> 只是新版的评论样式会被父级影响，比如父级div textAlign={"center"}，评论内容都居中了

这一块我是没动过的。

> 另外这个配置 `commentClassName: 'prose prose-neutral dark:prose-invert min-w-0 max-w-none'` 是UnoCSS 相关的类吗？不熟悉这个css。

这里这个配置是对每一条评论加上的，你可以自己写样式，然后配置类名。如果装了 UnoCSS 的话，UnoCSS 会识别这里面的内容并且加上类名，但不太清楚 tailwindcss 的行为。
